export const ORDER_CREAR_REQUEST = "ORDER_CREAR_REQUEST"
export const ORDER_CREAR_SUCCESS = "ORDER_CREAR_SUCCESS"
export const ORDER_CREAR_FAIL = "ORDER_CREAR_FAIL"
export const ORDER_CREAR_RESET = "ORDER_CREAR_RESET"

export const ORDER_DETALLE_REQUEST = "ORDER_DETALLE_REQUEST"
export const ORDER_DETALLE_SUCCESS = "ORDER_DETALLE_SUCCESS"
export const ORDER_DETALLE_FAIL = "ORDER_DETALLE_FAIL"

export const ORDER_PAGO_REQUEST = "ORDER_PAGO_REQUEST"
export const ORDER_PAGO_SUCCESS = "ORDER_PAGO_SUCCESS"
export const ORDER_PAGO_FAIL = "ORDER_PAGO_FAIL"
export const ORDER_PAGO_RESET = "ORDER_PAGO_RESET"

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST"
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS"
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL"
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET"