export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTRO_REQUEST = "USER_REGISTRO_REQUEST"
export const USER_REGISTRO_SUCCESS = "USER_REGISTRO_SUCCESS"
export const USER_REGISTRO_FAIL = "USER_REGISTRO_FAIL"

export const USER_DETALLE_REQUEST = "USER_DETALLE_REQUEST"
export const USER_DETALLE_SUCCESS = "USER_DETALLE_SUCCESS"
export const USER_DETALLE_FAIL = "USER_DETALLE_FAIL"
export const USER_DETALLE_RESET = "USER_DETALLE_RESET"

export const USER_ACTUALIZAR_REQUEST = "USER_ACTUALIZAR_REQUEST"
export const USER_ACTUALIZAR_SUCCESS = "USER_ACTUALIZAR_SUCCESS"
export const USER_ACTUALIZAR_FAIL = "USER_ACTUALIZAR_FAIL"
export const USER_ACTUALIZAR_RESET = "USER_ACTUALIZAR_RESET"